### ISSUE TITLE
How to appropriately turn on and off color bars

### ISSUE THREAD

**Issue by andyrbarrow** [metocean/wxtiles#3]
I've built a project that uses a checkbox to turn WXTiles on and off. Untortunately, while the overlays act as expected, the colorbars stay on the screen, stacking up on the side with each on/off cycle.

I'm looking for a little help in which API commands I can use to also switch the colorbars on and off.

The site is here: http://www.vallartayachtclub.org/weather-and-tides/842-storm-track-and-general-weather-2

Checking and un-checking WXTiles on the top of the map will demonstrate the issue.

**Comment by fiendish** [comment]
Loading your page and clicking the checkbox produce javascript console errors.

**Comment by andyrbarrow** [comment]
One of the errors is a 500 error, the API is trying to fetch a color bar that doesn't exist. This happens on both the satellite overlays. 
GET http://sat.wxtiles.com/satir/big/vert 500 (Server error)

I tried loading the API js file on my server and putting in some code to catch that, but it didn't work. Since the page was still loading, I didn't worry about it. the problem I'm describing is when I try one of the views that generates a vertical color bar on the right side. When I check/uncheck, the color bar doesn't go away.

**Comment by fiendish** [comment]
> One of the errors is a 500 error

But not all of them.

I saw the problem you describe and your code produces a JavaScript error
when you uncheck the box. Do you know that you're passing map to a function
that wants a bool on uncheck?

> Since the page was still loading, I didn't worry about it.

You should perhaps worry about it. It creates ugly missing image icons.

**Comment by tcoats** [comment]
Hi @andyrbarrow, I hope things are working for you. Feel free to reply with more questions otherwise.
