### ISSUE TITLE
Probleme with wxtiles and Google Maps Api

### ISSUE THREAD

**Issue by snak31** [metocean/wxtiles#4]
Hey guys, i want use wxtiles api for Google maps, but me map exe in IE7, and if IE is inferior at IE10 WXtile not working :( Help me please

**Comment by tcoats** [comment]
I'm not following your issue very well, can you provide more detail?

Are you trying to get something working in Internet Explorer 7?

**Comment by snak31** [comment]
I developped a mapping application , I have a script that I use for all of the function I add for mapping, and I would like to add your script that are great, but if I put my IE10 compatibility function no longer walk and I do not know why and if I put in IE7 it's yours that does not go :(

Sorry for English I use Google translation : S

**Comment by tcoats** [comment]
Can you post both error messages?
If they are large use https://gist.github.com/

**Comment by snak31** [comment]
I have no error message , just the selection fields that do not complete and I have not the image that appears on satelite

**Comment by tcoats** [comment]
Can you link to the two versions of your website that don't work? Or send through the website code so I can have a look?

It sounds like it might be something unrelated to wxtiles, but I can't be sure without looking at the code.

**Comment by snak31** [comment]
https://gist.github.com/b5507dd6b08b0d238927.git

Me code :)

**Comment by tcoats** [comment]
Hi @snak31 - thanks for sharing your code.
I believe to setup the project I need more files including:
- Script/markerwithlabel.js
- Script/ScriptMap.js
- Script/arcgislink.js

**Comment by tcoats** [comment]
Hi @snak31 I'm going to close this issue - but feel free to continue to comment and I'll open it again if needed.
