### ISSUE TITLE
wmapdemo Time Stepping forward and back

### ISSUE THREAD

**Issue by PSGRaptor** [metocean/wxtiles#6]
**Is there a working Demo available** where the _Time Stepping control actually works_. Running the demo wmapdemo.html in a browser and clicking on the arrow buttons has no effect at all. Time data is not visible and map overlay does not change.
![wmapdemo](https://cloud.githubusercontent.com/assets/1025921/12544494/e63528b8-c33a-11e5-8c30-920066c3e99c.jpg)

**Comment by tcoats** [comment]
Hi @PSGRaptor sorry for the late reply.

I've fixed the example to point to the correct server address (61f93d984a5dde5f50f6d7826b55be173e4919c8). We had made some changes and the examples were not up to date.

If you get latest things should be working now.
