### ISSUE TITLE
Satelite IR/Satelite IR Enhanced not showing around Australia?

### ISSUE THREAD

**Issue by Popsikill** [metocean/wxtiles#7]
Hi there,

I've got an issue where the tiles are not showing on a strip including australia - see the attached image.

As this also seems to be the case on your demo I believe this maybe a bug?

Any help would be greatly appreciated :)

![wxtiles](https://cloud.githubusercontent.com/assets/5036005/13796514/55e64eec-eb5b-11e5-801b-7750011eb32a.PNG)

**Comment by Popsikill** [comment]
Air Temperature also seems to only be showing on US/Canada..

**Comment by alpha-beta-soup** [comment]
Hi @Popsikill, the satellite issue is temporary, we are currently working to restore coverage over that region. Different geostationary satellites are responsible for different regions, so that's why there's a gap in that particular strip and not the rest of the planet.

The temperature tiles are working OK at my end. If you haven't already, try zooming, panning, changing the timestep, or adding/removing the layer to see if that triggers the tiles to be reloaded.

**Comment by Popsikill** [comment]
Cheers guys, looks like it's back up and running :)

Not sure what happened with the Air Temp - I didn't change my end at all but it is not as it should be - would the satellite issue have anything to do with that?

Thanks for your hard work, these overlays for Google Maps are 1000 times better than OpenWeatherMap :)

**Comment by alpha-beta-soup** [comment]
Is the air temperature layer still not functioning for you, @Popsikill? If it is working, feel free to close this issue.

Also, are you able to share a link to your application? It's helpful for us to see how the layers are being used, particularly at the moment as we're putting work in to improve our map tiles. No worries if you can't or don't want to share.

**Comment by Popsikill** [comment]
The Air Temperature layer seemed to have come right around the same time of the satellite fix - so all is well with the world (sorry I like puns).

Unfortunately the site is currently only on our internal network - just a little something to help our helpdesk team with their day to day tasks and it's great they are able to see weather on some of our client sites.

(I have added out public IP to your WXTiles site to comply with your conditions and ultimately we will be making it public for our onsite guys to help with their work).

Thanks for your help guys!
